### PR TITLE
native:fix include of nativebase/nativebase.h

### PR DESCRIPTION
**Pull request by mg712702**

### CODE REVIEW

**Comment by TheDarkStrix** [comment]
What was the issue ?

**Comment by mg712702** [comment]
Fatal error: file not found

**Comment by TheDarkStrix** [comment]
Which hals are u using ? 89xx | which one ?

**Comment by mg712702** [comment]
8916

**Comment by TheDarkStrix** [comment]
https://review.lineageos.org/#/c/202347/ pick this and build

**Comment by mg712702** [comment]
Ok

**Pull request closed without merging**
